// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGxO9g5qWo79TKi1kbSxGZjeY7NJA2ZdA',
    appId: '1:535853790260:web:67a20a63a75c987ac00661',
    messagingSenderId: '535853790260',
    projectId: 'hetanshi-enterprice',
    authDomain: 'hetanshi-enterprice.firebaseapp.com',
    storageBucket: 'hetanshi-enterprice.firebasestorage.app',
    measurementId: 'G-CEP300S9TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1fvhEPy6l0eVRYADw02sT73rUWMcYGsU',
    appId: '1:535853790260:android:c023a64df7daa542c00661',
    messagingSenderId: '535853790260',
    projectId: 'hetanshi-enterprice',
    storageBucket: 'hetanshi-enterprice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPh02nCWEFjECRTLhIx1t79cIDXtJQfmg',
    appId: '1:535853790260:ios:2f46ea15a03b517ec00661',
    messagingSenderId: '535853790260',
    projectId: 'hetanshi-enterprice',
    storageBucket: 'hetanshi-enterprice.firebasestorage.app',
    iosBundleId: 'com.example.hetanshiEnterprise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPh02nCWEFjECRTLhIx1t79cIDXtJQfmg',
    appId: '1:535853790260:ios:2f46ea15a03b517ec00661',
    messagingSenderId: '535853790260',
    projectId: 'hetanshi-enterprice',
    storageBucket: 'hetanshi-enterprice.firebasestorage.app',
    iosBundleId: 'com.example.hetanshiEnterprise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGxO9g5qWo79TKi1kbSxGZjeY7NJA2ZdA',
    appId: '1:535853790260:web:0a64ba04a22b18d9c00661',
    messagingSenderId: '535853790260',
    projectId: 'hetanshi-enterprice',
    authDomain: 'hetanshi-enterprice.firebaseapp.com',
    storageBucket: 'hetanshi-enterprice.firebasestorage.app',
    measurementId: 'G-WEJVL95E56',
  );
}
